// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5IqxUUbhOyYKxvUzkGu_wMHq64_kHYU',
    appId: '1:1039973486822:web:94e7a9824610f393132b27',
    messagingSenderId: '1039973486822',
    projectId: 'canvas-ae937',
    authDomain: 'canvas-ae937.firebaseapp.com',
    storageBucket: 'canvas-ae937.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1g6hcbI8ewjkOhvrtx4bsZtwi99OmC8',
    appId: '1:1039973486822:android:aa63df3767f21ee0132b27',
    messagingSenderId: '1039973486822',
    projectId: 'canvas-ae937',
    storageBucket: 'canvas-ae937.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY5IqxUUbhOyYKxvUzkGu_wMHq64_kHYU',
    appId: '1:1039973486822:web:4ca1bff77214ef1c132b27',
    messagingSenderId: '1039973486822',
    projectId: 'canvas-ae937',
    authDomain: 'canvas-ae937.firebaseapp.com',
    storageBucket: 'canvas-ae937.firebasestorage.app',
  );
}
